Team-MID-in-SKHU/MID-Backend

- MID_SKHU/src/main/java/com/skhu/mid_skhu/global/jwt/JwtFilter.java
작업 배경
- Git Flow를 이해하기 위해 Commit 및 PR을 수행해봅니다
- #2
> [Setting] #2 - Git Flow를 이해하기 위해 Test합니다.

- MID_SKHU/src/main/java/com/skhu/mid_skhu/entity/user/Student.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/global/common/advice/ControllerExceptionAdvice.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/global/common/dto/ApiResponse.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/service/auth/LoginService.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/service/auth/SignUpService.java
- ApiResponse를 수정했습니다
- ControllerExceptionAdvice를 수정했습니다
- Reslove: #9
> [fix] #9 - modified ApiResponse, ControllerExceptionAdvice

- MID_SKHU/src/main/java/com/skhu/mid_skhu/entity/interest/Interest.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/entity/interest/InterestCategory.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/entity/user/Student.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/global/jwt/JwtFilter.java
-  데이터베이스 설계를 수정했습니다
- 관심사 카테고리를 enum타입으로 만들었습니다.
- Interest 엔티티와 연관괸계를 설정해줬습니다
- 기타 초기설정
🍀 관련 이슈
Resolved: #7
> [setting] #7 modified database design

- MID_SKHU/src/main/java/com/skhu/mid_skhu/controller/auth/AuthController.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/controller/interest/InterestController.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/global/common/advice/ControllerExceptionAdvice.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/global/common/dto/ApiResponseTemplate.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/service/auth/SignUpService.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/service/interest/InterestRegisterService.java
-  swagger api 문서 수정
- swagger api 문서를 수정했습니다
- reponse HttpStatusCode 별로 대응 방법에 대한 description을 추가했습니다.
🍀 관련 이슈
Resolved: #17
> [docs]: #17 modified swagger api docs

- MID_SKHU/src/main/java/com/skhu/mid_skhu/controller/auth/AuthController.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/dto/auth/RefreshTokenParsingDto.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/dto/auth/RenewAccessTokenDto.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/dto/auth/requestDto/LoginRequestDto.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/dto/auth/responseDto/LoginResponseDto.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/global/exception/ErrorCode.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/repository/StudentRefreshTokenRepository.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/repository/StudentRepository.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/service/auth/LoginService.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/service/auth/TokenRenewService.java
-  login api 제작
- 회원가입을 진행한 후 로그인하는 api를 개발했습니다
- 암호화된 비밀번호와 매칭이 되는지에 대해서 검증하는 기능이 있습니다
🍀 관련 이슈
Resolved: #8
> [feat] #8 login api develop

- MID_SKHU/src/main/java/com/skhu/mid_skhu/controller/auth/AuthController.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/dto/auth/requestDto/StudentNoDuplicateInspectionRequestDto.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/dto/auth/responseDto/StudentNoDuplicateInspectionResponseDto.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/service/auth/LoginService.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/service/auth/SignUpService.java
-  학번 중복검사 api 제작
- 회원가입을 진행하는 도중에 학번 중복검사에 쓰일 api를 개발했습니다
🍀 관련 이슈
Resolved: #8
> [feat] #8 studentNumber duplicateInspection api develop

- MID_SKHU/src/main/java/com/skhu/mid_skhu/entity/student/Student.java
-  Student Entity 수정
- Student Entity에서 studentNo(학번)의 컬럼 세팅을 변경했습니다.
- 컬럼 세팅에서 unique옵션을 추가했습니다.
🍀 관련 이슈
Resolved: #7
> [setting] #7 modified studentNo Column from Student entity

- MID_SKHU/src/main/java/com/skhu/mid_skhu/entity/event/Event.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/entity/interest/Interest.java
-  Entity 수정
- Event Entity와 Interest Entity와의 연관관계를 추가했습니다
- Event Entity에서 장소를 작성할 수 있는 컬럼을 추가했습니다
🍀 관련 이슈
Resolved: #7
> [setting] #7 : modify database setting

- MID_SKHU/build.gradle
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/controller/user/SmsCertificationController.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/dto/user/UserSmsDto.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/repository/SmsCertificationDao.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/service/user/UserCertificationService.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/service/user/UserCertificationServiceImpl.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/global/aop/TimeTraceAop.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/global/common/dto/ApiResponseTemplate.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/global/config/RedisConfig.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/global/exception/ErrorCode.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/global/exception/SuccessCode.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/global/util/SmsCertificationUtil.java
- MID_SKHU/src/main/resources/application.yml
-  sms 인증을 구현했습니다
- sms를 통해서 인증하는 과정을 개발했습니다
- 문자 발송 api
- 문자 인증 api
🍀 관련 이슈
Resolved: #25
> [feature] #25 sms certification api

- MID_SKHU/src/main/resources/application.yml
-  환경변수 수정했습니다
- yml에 설정된 데이터를 환경변수화 했습니다
- deployment pipline setting
🍀 관련 이슈
Resolved: #25
> [feature] #25 modify environment variable and yml

- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/controller/user/UserInfoController.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/dto/user/responseDto/UserInfoResponseDto.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/service/user/UserInfoService.java
-  마이페이지 조회 기능을 위한 userInfo api 구현
- 마이페이지 정보를 조회하는 api를 개발했습니다 (사용자의 학번, 이름, 타입 정보를  반환)
- Postman을 사용하여 테스트 완료했습니다
🍀 관련 이슈
Resolved: #31
> [feature] #31 userInfo api

- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/controller/event/EventCreateForAdminController.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/controller/interest/InterestController.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/dto/event/requestDto/EventCreateRequestDto.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/dto/event/responseDto/EventCreateResponseDto.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/entity/event/Event.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/entity/interest/Interest.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/entity/interest/InterestCategory.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/entity/student/Student.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/repository/EventRepository.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/repository/InterestRepository.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/service/event/EventCreateForAdminService.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/service/interest/InterestRegisterService.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/global/config/SecurityConfig.java
- MID_SKHU/src/test/java/com/skhu/mid_skhu/app/entity/interest/InterestCategoryTest.java
-  이벤트를 등록하는 api 개발
- event를 등록하는 api를 개발했습니다 - only admin
- 약간의 domain수정이 있습니다 (추후에 domain 수정이 더 이루어질 예정입니다)
🍀 관련 이슈
Resolved: #33
> [feature] #33 event create api

- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/controller/user/UserInfoController.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/dto/event/EventDto.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/dto/user/requestDto/UserTodoListRequestDto.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/dto/user/responseDto/UserTodoListResponseDto.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/dto/user/responseDto/UserTodoListWrapperResponseDto.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/repository/EventRepository.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/service/auth/LoginService.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/service/user/UserTodoListCheckService.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/global/exception/ErrorCode.java
- 나의 일정을 조회하는 api를 개발했습니다
- 클라이언트로부터 token을 받아와 사용자 본인이 등록한 관심사와 일치하거나 포함된 이벤트들을 불러옵니다
- modified -> etc docs, ErrorMessage 
🍀 관련 이슈
Resolved: #37
> [feature] #37 UserTodoListCheck Api

- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/controller/event/EventCreateForAdminController.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/controller/event/EventForUserController.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/dto/event/requestDto/EventSearchRequestDto.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/dto/event/responseDto/EventSearchResponseDto.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/entity/event/Event.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/entity/interest/Interest.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/entity/interest/InterestCategory.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/entity/student/Student.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/repository/EventRepository.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/repository/EventSpecification.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/repository/specification/EventSpecification.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/service/event/EventCreateForAdminService.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/service/event/EventSearchService.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/service/user/UserTodoListCheckService.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/global/exception/ErrorCode.java
- 이벤트 / 행사를 검색하는 api를 개발했습니다
- 이벤트 행사를 제목 / 날짜 / 관심사 별로 검색할 수 있도록 했습니다
- 행사 / 날짜 / 관심사 중 빈 값으로 넘어오는 값은 검색 필터에서 제외하고 검색 할 수 있도록 했습니다.
🍀 관련 이슈
Resolved: #39
> [Feature] #39 development of Api Search For Event

- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/controller/user/UserDetailsController.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/dto/user/requestDto/UserDetailsUpdateRequestDto.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/dto/user/responseDto/UserDetailsResponseDto.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/entity/student/Student.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/service/user/UserDetailsService.java
-  사용자 상세 정보를 조회/수정하기 위한 userDetails api 구현
- 사용자 상세 정보를 조회/수정하는 api를 개발했습니다
- Postman을 사용하여 테스트 완료했습니다
🍀 관련 이슈
Resolved: #43
> [feature] #43 userDetails api

- MID_SKHU/build.gradle
- MID_SKHU/src/main/java/com/skhu/mid_skhu/MidSkhuApplication.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/controller/fcm/FcmController.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/dto/fcm/FcmMessage.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/dto/fcm/FcmRequestDto.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/entity/student/Student.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/repository/EventRepository.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/repository/StudentRepository.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/service/fcm/EventPushAlarmSchedulerService.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/service/fcm/FirebaseCloudMessageService.java
- MID_SKHU/src/main/resources/application.yml
- Firebase Cloud Message를 기본 세팅을 진행했습니다
- 환경변수를 추가했습니다
- 의존성을 새로 주입했습니다
- 행사 시간 3시간 전에 알람을 보내는 기능까지만 구현했습니다
하루 일정을 조회하는 api를 개발후에 수정하고 완성하도록 하겠습니다.
🍀 관련 이슈
Resolved: #46
> [Feature] #46 fcm base setting

- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/dto/auth/requestDto/LoginRequestDto.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/dto/auth/requestDto/SignUpRequestDto.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/service/auth/SignUpService.java
- 회원가입과 로그인 프로세스에서 fcm토큰을 받습니다
- 회원가입 과정에서 fcmToken을 받고 저장합니다
- Login과정에서 fcmToken을 받고 저장합니다
🍀 관련 이슈
Resolved: #49
> Fix#49 Add FcmToken during SignUp, Login process

- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/service/auth/LoginService.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/service/fcm/EventPushAlarmSchedulerService.java
delete commentary, an unnecessary line
> delete commentary, an unnecessary line

- MID_SKHU/src/main/java/com/skhu/mid_skhu/global/config/SwaggerApiConfig.java
작업한 내용: 수정이 되지 않은 swagger api docs description을 수정했습니다.
관련 이슈: #17
> modify swagger config description

- .github/workflows/build.yml
제목: 빌드 업무를 수정했습니다
작업한 내용: docker image를 통해서 업로드 될 때 이 전 docker이미지를 변수에 저장하고 이전 이미지 파일을 제거해서
용량을 관리 할 수 있도록 했습니다
이유: docker image파일들이 삭제가 되지 않으면 인스턴스 내부에서 용량이 초과되어 새롭게 반영이 안되는 문제가 발생했기에
> [chore] #46 modify docker image yml

- .github/workflows/build.yml
> chore: modify docker image yml3

- .github/workflows/build.yml
> chore: modify docker image yml4

- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/controller/fcm/FcmController.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/dto/auth/requestDto/SignUpRequestDto.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/dto/user/responseDto/UserDetailsResponseDto.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/dto/user/responseDto/UserInfoResponseDto.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/entity/student/Student.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/service/auth/SignUpService.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/service/user/UserDetailsService.java
- MID_SKHU/src/main/java/com/skhu/mid_skhu/app/service/user/UserInfoService.java
- Student Entity에 deparment(학부) 정보를 받을 수 있도록 수정했습니다
- entity에 column 추가
- 회원가입, 사용자 정보 조회, 사용자 정보 상세 조회 등에 사용되는 dto의 필드를 수정했습니다.
🍀 관련 이슈
Resolved: #8, #7
> Feature#8 add Student Entity Column
